import test from "node:test";
import assert from "node:assert/strict";
import { closeCursor, collectMatching, dragDistribute, emptySlots, leftClick, quickMove, rightClick, stack } from "../client/src/inventory.js";

test("left click picks up, merges, and swaps",()=>{let slots=emptySlots(3);slots[0]=stack("stone",40);let r=leftClick(slots,0,null);assert.equal(r.cursor.count,40);assert.equal(r.slots[0],null);r=leftClick([stack("stone",40),null,null],0,stack("stone",30));assert.equal(r.slots[0].count,64);assert.equal(r.cursor.count,6);r=leftClick([stack("dirt",2),null,null],0,stack("stone",3));assert.equal(r.slots[0].id,"stone");assert.equal(r.cursor.id,"dirt");});
test("right click uses ceil half and places one",()=>{let r=rightClick([stack("stone",9)],0,null);assert.equal(r.cursor.count,5);assert.equal(r.slots[0].count,4);r=rightClick([null],0,stack("stone",3));assert.equal(r.slots[0].count,1);assert.equal(r.cursor.count,2);});
test("quick move merges before filling and preserves remainder",()=>{const source=[stack("stone",20)];const target=[stack("stone",60),null];const r=quickMove(source,0,target,[0,1]);assert.equal(r.source[0],null);assert.equal(r.target[0].count,64);assert.equal(r.target[1].count,16);});
test("quick move within one inventory moves main to hotbar",()=>{const slots=emptySlots(36);slots[0]=stack("dirt",5);const r=quickMove(slots,0,slots,[27,28,29,30,31,32,33,34,35]);assert.equal(r.source[0],null);assert.equal(r.source[27].count,5);});
test("double collect caps at max",()=>{const groups=[[stack("stone",30),stack("stone",30)],[stack("stone",30)]];const r=collectMatching(groups,stack("stone",10));assert.equal(r.cursor.count,64);assert.equal(r.groups.flat().filter(Boolean).reduce((n,s)=>n+s.count,0),36);});
test("drag distribution supports even and one modes",()=>{let r=dragDistribute(emptySlots(3),[0,1,2],stack("dirt",10),"even");assert.deepEqual(r.slots.map(s=>s?.count),[3,3,3]);assert.equal(r.cursor.count,1);r=dragDistribute(emptySlots(4),[0,1,2,3],stack("dirt",3),"one");assert.deepEqual(r.slots.map(s=>s?.count),[1,1,1,undefined]);assert.equal(r.cursor,null);});
test("closing cursor returns to player then exposes overflow",()=>{const slots=emptySlots(36);slots[0]=stack("stone",60);const r=closeCursor(slots,stack("stone",10));assert.equal(r.player[0].count,64);assert.equal(r.player[1].count,6);assert.equal(r.dropped,null);});
