import test from"node:test";import assert from"node:assert/strict";import{emptySlots,defaultPlayerInventory}from"../client/src/inventory.js";import{RECIPES,craftRecipeFromPlayer,matchRecipe}from"../client/src/inventory/crafting.js";import{deriveContextExperience}from"../client/src/dsh/projections.js";import{classifyToolActivity}from"../client/src/dsh/tool-activity-router.js";import{selectCommunityLoot}from"../client/src/dsh/community-loot.js";import{deriveRunningWork,runningWorkList}from"../client/src/dsh/npc-roster.js";import{generateWorld}from"../client/src/world.js";import{DROP_PICKUP_DELAY,canPickupDrop,dropLaunchVelocity}from"../client/src/drop-physics.js";
test("3x3 workbench recipes match and consume inventory",()=>{const recipe=RECIPES.find(x=>x.id==="stone_pickaxe"),grid=emptySlots(9);[0,1,2].forEach(i=>grid[i]={id:"stone",count:1});grid[4]={id:"stick",count:1};grid[7]={id:"stick",count:1};assert.equal(matchRecipe(grid)?.id,"stone_pickaxe");const flat=defaultPlayerInventory(),player={main:flat.slice(0,27),hotbar:flat.slice(27)};player.main[0]={id:"stick",count:2};const result=craftRecipeFromPlayer(player,recipe);assert.equal(result.ok,true);assert.ok([...result.player.main,...result.player.hotbar].some(x=>x?.id==="stone_pickaxe"));});
test("context experience uses projected pressure and billing buckets",()=>{const x=deriveContextExperience({projectedTokens:750,pressureTokens:500,contextWindow:1000},{uncachedInputTokens:10,cacheReadTokens:20,cacheWriteTokens:5,outputTokens:15},{systemTokens:2});assert.equal(x.percent,75);assert.equal(x.inputTokens,35);assert.equal(x.totalTokens,50);assert.equal(x.breakdown.systemTokens,2);});
test("tool calls route to four semantic facilities",()=>{assert.equal(classifyToolActivity("read").facility,"bookshelf");assert.equal(classifyToolActivity("pwsh").facility,"terminal");assert.equal(classifyToolActivity("web_search").facility,"cartography");assert.equal(classifyToolActivity("edit").facility,"workbench");assert.equal(classifyToolActivity("mystery").facility,null);});
test("community chest loot is deterministic and unique",()=>{const items=Array.from({length:20},(_,i)=>({id:`p${i}`}));const a=selectCommunityLoot(items,42,9),b=selectCommunityLoot(items,42,9);assert.deepEqual(a.map(x=>x.id),b.map(x=>x.id));assert.equal(new Set(a.map(x=>x.id)).size,9);});
test("wilderness plugins stay represented by static community chest blocks",()=>{const world=generateWorld(1337),community=world.chests.filter(x=>x.kind==="community");assert.ok(community.length>0);assert.ok(community.every(chest=>world.blocks.get(chest.key)==="community_chest"));});
test("only running work becomes a dog and newest work comes first",()=>{const rows=[{id:"idle",running:false,updatedAt:9},{id:"run1",displayTitle:"Build",running:true,updatedAt:2},{id:"run2",displayTitle:"Review",running:true,updatedAt:5}],snapshots=new Map([["run1",{partial:{blocks:[{kind:"reasoning",text:"checking the implementation"}]} }],["run2",{runningCalls:[{callId:"c1",name:"edit"}]}]]),work=runningWorkList(rows,snapshots);assert.deepEqual(work.map(x=>x.sessionId),["run2","run1"]);assert.equal(work[0].progress,"工具 · edit");assert.equal(work[1].progress,"思考 · checking the implementation");});
test("latest Agent progress supports text pending queue and generic final nodes",()=>{const row={id:"s",displayTitle:"Work",running:true};assert.match(deriveRunningWork(row,{partial:{blocks:[{kind:"text",text:"shipping now"}]}}).progress,/shipping now/);assert.equal(deriveRunningWork(row,{pending:[{kind:"approval"}]}).progress,"等待操作批准");assert.equal(deriveRunningWork(row,{queue:[{},{}]}).progress,"队列 · 2 条消息");assert.equal(deriveRunningWork(row,{nodes:[{kind:"compaction"}]}).progress,"正在整理上下文");});
test("world drops wait briefly then auto-pick only at close range",()=>{const item={x:1,y:1,z:1},near={x:1.8,y:1,z:1},far={x:4,y:1,z:1};assert.equal(canPickupDrop(item,near,DROP_PICKUP_DELAY-.01),false);assert.equal(canPickupDrop(item,near,DROP_PICKUP_DELAY),true);assert.equal(canPickupDrop(item,far,2),false);const velocity=dropLaunchVelocity(0,.5);assert.ok(velocity.x>0);assert.equal(velocity.y,1.8);});
