import test from "node:test";
import assert from "node:assert/strict";
import { applyWorldSave, generateWorld, getBlock, playerSpawn, serializeWorld, setBlock, terrainHeight } from "../client/src/world.js";

test("terrain generation is deterministic",()=>{const a=generateWorld(42,8),b=generateWorld(42,8);assert.equal(a.blocks.size,b.blocks.size);assert.equal(terrainHeight(42,3,7),terrainHeight(42,3,7));assert.equal(getBlock(a,2,terrainHeight(42,2,2),2),getBlock(b,2,terrainHeight(42,2,2),2));});
test("world diffs survive serialization",()=>{const world=generateWorld(99,8);setBlock(world,1,12,1,"planks");setBlock(world,0,1,0,"air");const restored=applyWorldSave(serializeWorld(world),8);assert.equal(getBlock(restored,1,12,1),"planks");assert.equal(getBlock(restored,0,1,0),"air");});
test("legacy saves restore core facilities lost before self-drops",()=>{const base=generateWorld(1337,8),facility=base.facilities.cartography,legacy={version:1,seed:1337,diffs:[[facility.key,"air"]]},restored=applyWorldSave(legacy,8);assert.equal(getBlock(restored,facility.x,facility.y,facility.z),"cartography_table");const current=applyWorldSave({version:2,seed:1337,diffs:[[facility.key,"air"]]},8);assert.equal(getBlock(current,facility.x,facility.y,facility.z),"air");});
test("spawn is above solid terrain",()=>{const world=generateWorld(7,8);const p=playerSpawn(world);assert.equal(getBlock(world,Math.floor(p.x),Math.floor(p.y),Math.floor(p.z)),"air");assert.notEqual(getBlock(world,0,Math.floor(p.y)-1,0),"air");});
test("starter house exposes every DSHcraft facility",()=>{const world=generateWorld(7,8);assert.equal(world.structureVersion,2);for(const [name,type] of Object.entries({workbench:"crafting_table",modelChest:"model_chest",pluginChest:"plugin_chest",enchantTable:"enchant_table",bookshelf:"bookshelf",terminal:"terminal",cartography:"cartography_table",tutorial:"sign"})){const f=world.facilities[name];assert.ok(f,name);assert.equal(getBlock(world,f.x,f.y,f.z),type)}});
