import React,{useEffect,useMemo,useState,useSyncExternalStore}from"react";
import{createBridge}from"../bridge/client.js";
import{ModelChestScreen}from"./ModelChestScreen.jsx";
import{PluginChestScreen}from"./PluginChestScreen.jsx";
import{ToolMonitorScreen,WorkbenchScreen}from"./WorkbenchScreen.jsx";
import{WorkspaceMapScreen}from"./WorkspaceMapScreen.jsx";
import{CommunityLootChest}from"./CommunityLootChest.jsx";
const EMPTY={current:null,groups:[],failures:[],status:"idle",error:null};
function ModelDirectoryView({services,sessionId,mode,onClose}){const dir=useMemo(()=>{try{return sessionId&&services.modelDirectories?.directoryFor(sessionId)}catch{return null}},[services,sessionId]);const state=useSyncExternalStore(cb=>{const off=dir?.store?.subscribe(cb);return typeof off==="function"?off:()=>{}},()=>dir?.store?.getSnapshot()||EMPTY,()=>EMPTY);useEffect(()=>{dir?.load().catch(()=>{})},[dir]);const choices=state.groups.flatMap(g=>g.models.map(m=>({group:g,model:m}))),current=choices.find(x=>x.group.id===state.current?.provider&&x.model.id===state.current?.model);const select=async value=>{if(!dir)return;if(mode==="reasoning")await dir.select({...state.current,reasoningEffort:value});else await dir.select({provider:value.group.id,model:value.model.id,...(value.model.reasoning?.defaultEffort===undefined?{}:{reasoningEffort:value.model.reasoning.defaultEffort})})};if(!dir)return <FacilityFrame title={mode==="reasoning"?"附魔台":"模型宝箱"} onClose={onClose}><p className="mc-facility-error">当前 DSH 未提供模型目录；可在工作台输入 /model。</p></FacilityFrame>;if(mode==="reasoning"){const efforts=current?.model.reasoning?.efforts||[];return <FacilityFrame title="附魔台 · 推理强度" onClose={onClose}><div className="mc-enchant-slot"><span>⛑</span><b>{current?.model.name||state.current?.model||"未装备模型"}</b></div><div className="mc-enchant-list">{efforts.length?efforts.map((e,i)=><button key={e.id} className={state.current?.reasoningEffort===e.id?"active":""} disabled={state.status==="selecting"} onClick={()=>select(e.id)}><i>{["迅捷 I","思索 II","深思 III","神思 IV"][i]||e.name}</i><b>{e.name}</b><small>{e.description||e.id}</small></button>):<p>这个模型无法附魔推理强度。</p>}</div>{state.error&&<p className="mc-facility-error">{state.error}</p>}</FacilityFrame>}
return <FacilityFrame title="模型宝箱 · 装备主模型" onClose={onClose}><div className="mc-model-grid">{choices.map(x=><button key={`${x.group.id}/${x.model.id}`} className={state.current?.provider===x.group.id&&state.current?.model===x.model.id?"equipped":""} disabled={state.status==="selecting"} onClick={()=>select(x)}><span className="mc-model-helmet">⛑</span><b>{x.model.name}</b><small>{x.group.name}</small>{x.model.description&&<em>{x.model.description}</em>}</button>)}</div>{state.status==="loading"&&<p>正在读取已配置模型…</p>}{state.error&&<p className="mc-facility-error">{state.error}</p>}</FacilityFrame>}
function CapabilityChest({services,sessionId,onClose}){const bridge=useMemo(()=>createBridge(services.connection),[services]),[state,setState]=useState({loading:true,items:[],error:""});const load=()=>bridge.listCapabilities(sessionId).then(v=>setState({loading:false,items:v.items||[],error:""})).catch(e=>setState({loading:false,items:[],error:String(e)}));useEffect(()=>{load()},[sessionId]);const toggle=async item=>{if(item.locked)return;setState(s=>({...s,loading:true}));try{const v=await bridge.setCapability(sessionId,item.id,!item.enabled);setState({loading:false,items:v.items||[],error:""})}catch(e){setState(s=>({...s,loading:false,error:String(e)}))}};return <FacilityFrame title="插件箱 · Agent 能力" onClose={onClose}><p className="mc-facility-hint">拿出物品即启用，放回箱中即禁用；只影响当前 Agent。</p><div className="mc-plugin-grid">{state.items.map(item=><button key={item.id} className={item.enabled?"enabled":"disabled"} onClick={()=>toggle(item)} disabled={state.loading||item.locked}><span>{item.locked?"🔒":item.enabled?"✦":"◇"}</span><b>{item.name}</b><small>{item.description||"DSH Tool"}</small><em>{item.locked?"由 Agent 内部管理":item.enabled?"已装备":"箱内 / 已禁用"}</em></button>)}</div>{state.loading&&<p>正在同步 Agent 装备…</p>}{state.error&&<p className="mc-facility-error">{state.error}</p>}</FacilityFrame>}
function Tutorial({onClose}){return <FacilityFrame title="欢迎来到 DSHcraft" onClose={onClose}><div className="mc-book-page"><h2>你的 Agent 世界</h2><p>① 打开蓝色模型箱，装备真实模型。</p><p>② 把模型带到附魔台，选择思考强度。</p><p>③ 打开紫色插件箱，启用 Agent 工具。</p><p>④ 右键中央工作台，开始真实 DSH 对话。</p><p>工具调用发生时，Coder 会走向书架、工作台或终端。</p><small>WASD 移动 · 空格跳跃 · 右键交互 · E 背包 · T 聊天</small></div></FacilityFrame>}
function FacilityFrame({title,onClose,children}){useEffect(()=>{const key=e=>{if(e.key==="Escape"||e.code==="KeyE"){e.preventDefault();e.stopPropagation();onClose()}};window.addEventListener("keydown",key,true);return()=>window.removeEventListener("keydown",key,true)},[onClose]);return <div className="mc-facility-shade"><section className="mc-facility"><header><h1>{title}</h1><button onClick={onClose}>×</button></header><div className="mc-facility-body">{children}</div></section></div>}
export function FacilityScreen({type,services,sessionId,sessions=[],workspaces=[],conversation,communityChest,player,onCraft,onNavigate,onClose}){if(type==="workbench")return <WorkbenchScreen player={player} onCraft={onCraft} onClose={onClose}/>;if(type==="workspace-map")return <WorkspaceMapScreen services={services} workspaces={workspaces} sessions={sessions} currentSessionId={sessionId} onClose={onClose}/>;if(type==="community")return <CommunityLootChest services={services} chest={communityChest} onClose={onClose}/>;if(type==="models")return <ModelChestScreen services={services} sessionId={sessionId} onClose={onClose}/>;if(type==="capabilities")return <PluginChestScreen services={services} sessionId={sessionId} onClose={onClose}/>;if(type==="reasoning")return <ModelDirectoryView services={services} sessionId={sessionId} mode={type} onClose={onClose}/>;if(type==="terminal")return <ToolMonitorScreen conversation={conversation} onClose={onClose}/>;if(type==="tutorial")return <Tutorial onClose={onClose}/>;return null}
export function PendingOverlay({wait}){const[busy,setBusy]=useState(false),[error,setError]=useState(""),[drafts,setDrafts]=useState({});if(!wait)return null;const send=async result=>{setBusy(true);setError("");try{const receipt=await wait.respond(result);if(!receipt.accepted)throw new Error(receipt.reason||"响应被拒绝")}catch(e){setBusy(false);setError(String(e))}};if(wait.kind==="approval"){const p=wait.payload;const answer=outcome=>send({ok:true,value:{sessionId:wait.sessionId,approvalId:p.approvalId,outcome}});return <div className="mc-pending"><section><h2>⚠ 红石权限请求</h2><b>{p.reason||`${p.toolName} 请求执行`}</b><code>{p.toolName}{p.callId?` · ${p.callId}`:""}</code>{error&&<p>{error}</p>}<footer><button disabled={busy} onClick={()=>answer("rejected")}>拒绝</button><button disabled={busy} className="allow" onClick={()=>answer("allowed-once")}>允许一次</button></footer></section></div>}
const questions=wait.payload.questions||[];const submit=()=>send({ok:true,value:{sessionId:wait.sessionId,answer:{answers:questions.map(q=>{const v=drafts[q.id]||"";return{ id:q.id,selected:(q.options||[]).some(o=>o.label===v)?[v]:[],...(v&&(q.options||[]).every(o=>o.label!==v)?{custom:v}:{})}})}}});return <div className="mc-pending"><section className="mc-question-book"><h2>📖 Agent 提问</h2>{questions.map(q=><label key={q.id}><b>{q.question}</b>{q.detail&&<small>{q.detail}</small>}<div>{(q.options||[]).map(o=><button type="button" className={drafts[q.id]===o.label?"active":""} onClick={()=>setDrafts(d=>({...d,[q.id]:o.label}))}>{o.label}</button>)}</div><input value={drafts[q.id]||""} onChange={e=>setDrafts(d=>({...d,[q.id]:e.target.value}))} placeholder="输入回答…"/></label>)}{error&&<p>{error}</p>}<footer><button disabled={busy} onClick={()=>send({ok:false,error:{code:"cancelled",message:"the user closed this question request",details:{}}})}>取消</button><button disabled={busy} className="allow" onClick={submit}>提交回答</button></footer></section></div>}

