import { cloneStack, maxStack } from "../inventory.js";
import { ARMOR_SLOTS, canPlace, canStack, clonePlayer, slotLimit, validatePlayer } from "./model.js";
import { consumeRecipe, craftingOutput, matchRecipe } from "./crafting.js";

const refs=(area,n)=>Array.from({length:n},(_,index)=>({area,index}));
export const MAIN_REFS=refs("main",27),HOTBAR_REFS=refs("hotbar",9),CHEST_REFS=refs("chest",27),CRAFT_REFS=refs("craft",4);
const PLAYER_STORE=[...MAIN_REFS,...HOTBAR_REFS];
function cloneState(s){return{player:clonePlayer(s.player),chest:(s.chest||[]).map(cloneStack),cursor:cloneStack(s.cursor),drag:s.drag?{...s.drag,refs:[...s.drag.refs]}:null};}
function get(s,r){if(r.area==="main"||r.area==="hotbar")return s.player[r.area][r.index];if(r.area==="craft")return s.player.crafting[r.index];if(r.area==="armor")return s.player.armor[r.slot];if(r.area==="offhand")return s.player.offhand;if(r.area==="chest")return s.chest[r.index];if(r.area==="output")return craftingOutput(s.player.crafting);return null;}
function set(s,r,v){v=cloneStack(v);if(r.area==="main"||r.area==="hotbar")s.player[r.area][r.index]=v;else if(r.area==="craft")s.player.crafting[r.index]=v;else if(r.area==="armor")s.player.armor[r.slot]=v;else if(r.area==="offhand")s.player.offhand=v;else if(r.area==="chest")s.chest[r.index]=v;}
function insert(s,value,targets){let rest=cloneStack(value);for(const r of targets){if(!rest)break;const t=get(s,r);if(!t||!canStack(t,rest)||t.count>=slotLimit(r,t)||!canPlace(r,rest))continue;const n=Math.min(rest.count,slotLimit(r,t)-t.count);set(s,r,{...t,count:t.count+n});rest.count-=n;if(!rest.count)rest=null;}for(const r of targets){if(!rest)break;if(get(s,r)||!canPlace(r,rest))continue;const n=Math.min(rest.count,slotLimit(r,rest));set(s,r,{...rest,count:n});rest.count-=n;if(!rest.count)rest=null;}return rest;}
function clickOutput(s,button,shift,effects){const recipe=matchRecipe(s.player.crafting),out=craftingOutput(s.player.crafting);if(!recipe||!out)return;if(shift){let guard=64;while(guard--&&matchRecipe(s.player.crafting)?.id===recipe.id){const rest=insert(s,out,PLAYER_STORE);if(rest)break;s.player.crafting=consumeRecipe(s.player.crafting,recipe);effects.push({type:"craft",recipeId:recipe.id,count:out.count});}return;}if(!s.cursor){s.cursor={...out};s.player.crafting=consumeRecipe(s.player.crafting,recipe);effects.push({type:"craft",recipeId:recipe.id,count:out.count});}else if(canStack(s.cursor,out)&&s.cursor.count+out.count<=maxStack(out)){s.cursor.count+=out.count;s.player.crafting=consumeRecipe(s.player.crafting,recipe);effects.push({type:"craft",recipeId:recipe.id,count:out.count});}}
function click(s,r,button){const t=get(s,r),c=s.cursor;if(button==="right"){if(!c&&t){const n=Math.ceil(t.count/2);s.cursor={...t,count:n};set(s,r,t.count===n?null:{...t,count:t.count-n});}else if(c&&!t&&canPlace(r,c)){set(s,r,{...c,count:1});c.count--;if(!c.count)s.cursor=null;}else if(c&&t&&canStack(c,t)&&t.count<slotLimit(r,t)&&canPlace(r,c)){set(s,r,{...t,count:t.count+1});c.count--;if(!c.count)s.cursor=null;}else if(c&&t&&canPlace(r,c)){set(s,r,c);s.cursor=t;}return;}if(!c){s.cursor=t;set(s,r,null);}else if(!t&&canPlace(r,c)){set(s,r,c);s.cursor=null;}else if(t&&canStack(t,c)&&t.count<slotLimit(r,t)&&canPlace(r,c)){const n=Math.min(c.count,slotLimit(r,t)-t.count);set(s,r,{...t,count:t.count+n});c.count-=n;if(!c.count)s.cursor=null;}else if(t&&canPlace(r,c)){set(s,r,c);s.cursor=t;}}
function shiftTargets(s,r,value){if(r.area==="chest")return PLAYER_STORE;if(s.chest.length&&["main","hotbar","armor","offhand"].includes(r.area))return CHEST_REFS;if(r.area==="armor"||r.area==="offhand"||r.area==="craft")return PLAYER_STORE;if(value){const slot=value&&Object.entries(s.player.armor).find(([k,v])=>!v&&value&&value.id&&canPlace({area:"armor",slot:k},value));if(slot)return[{area:"armor",slot:slot[0]}];}return r.area==="main"?HOTBAR_REFS:MAIN_REFS;}
function shiftClick(s,r){const value=get(s,r);if(!value)return;const rest=insert(s,value,shiftTargets(s,r,value));set(s,r,rest);}
function doubleCollect(s){if(!s.cursor)return;for(const r of [...CHEST_REFS,...CRAFT_REFS,...MAIN_REFS,...HOTBAR_REFS,...ARMOR_SLOTS.map(slot=>({area:"armor",slot})),{area:"offhand"}]){const t=get(s,r);if(!t||!canStack(t,s.cursor))continue;const n=Math.min(t.count,maxStack(s.cursor)-s.cursor.count);s.cursor.count+=n;set(s,r,t.count===n?null:{...t,count:t.count-n});if(s.cursor.count>=maxStack(s.cursor))break;}}
export function reduceContainer(previous,action){const s=cloneState(previous),effects=[];const r=action.ref;if(action.type==="CLICK"){if(r.area==="output")clickOutput(s,action.button,action.shift,effects);else if(action.shift)shiftClick(s,r);else click(s,r,action.button);}else if(action.type==="HOTBAR_SWAP"){const h={area:"hotbar",index:action.index};const a=get(s,r),b=get(s,h);if(canPlace(r,b)&&canPlace(h,a)){set(s,r,b);set(s,h,a);}}else if(action.type==="OFFHAND_SWAP"){const o={area:"offhand"};const a=get(s,r),b=get(s,o);if(canPlace(r,b)){set(s,r,b);set(s,o,a);}}else if(action.type==="DROP"){const t=r?get(s,r):s.cursor;if(t){const n=action.all?t.count:1;effects.push({type:"drop",stack:{...t,count:n}});const rest=t.count===n?null:{...t,count:t.count-n};r?set(s,r,rest):s.cursor=rest;}}else if(action.type==="DOUBLE_COLLECT")doubleCollect(s);else if(action.type==="DRAG_DISTRIBUTE"&&s.cursor){const unique=[];for(const ref of action.refs||[])if(!unique.some(x=>x.area===ref.area&&x.index===ref.index&&x.slot===ref.slot)){const t=get(s,ref);if(canPlace(ref,s.cursor)&&(!t||canStack(t,s.cursor)))unique.push(ref);}if(unique.length){const each=action.button==="right"?1:Math.floor(s.cursor.count/unique.length);if(each>0)for(const ref of unique){if(!s.cursor)break;const t=get(s,ref),room=slotLimit(ref,s.cursor)-(t?.count||0),n=Math.min(each,room,s.cursor.count);if(n>0){set(s,ref,t?{...t,count:t.count+n}:{...s.cursor,count:n});s.cursor.count-=n;if(!s.cursor.count)s.cursor=null;}}}}else if(action.type==="CLOSE"){s.drag=null;for(let i=0;i<s.player.crafting.length;i++){const value=s.player.crafting[i];if(!value)continue;const rest=insert(s,value,PLAYER_STORE);s.player.crafting[i]=null;if(rest)effects.push({type:"drop",stack:rest});}if(s.cursor){const rest=insert(s,s.cursor,PLAYER_STORE);if(rest)effects.push({type:"drop",stack:rest});s.cursor=null;}}validatePlayer(s.player);return{state:s,effects};}
